//! Source emission. Nothing in this module talks to a database — output is
//! a pure function of the catalog data in [`crate::introspect`] plus the
//! options here, which is what makes the renderers testable on their own.
//!
//! - [`model`] writes the row structs, their enum types, and the insert
//!   input types.
//! - [`children`] names the field a parent holds its child rows in, so
//!   the struct and the mapper method that fills it agree.
//! - [`mapper`] writes the repository struct that runs the queries.
//! - [`sql`] writes the migration defining the server-side functions the
//!   `Server` strategy calls.

use std::collections::{BTreeMap, BTreeSet};

use crate::config::Generate;
use crate::introspect::{Model, PgComposite, PgEnum};

pub mod children;
#[cfg(test)]
pub(crate) mod fixture;
pub mod mapper;
pub mod model;
pub mod plan;
pub mod python;
pub mod sql;

/// Which SQL the mapper runs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Strategy {
    /// The statements live in the Rust source.
    #[default]
    Embedded,
    /// The statements live in Postgres functions; the mapper calls them.
    /// Pair with [`sql::migration_file`], which defines those functions.
    Server,
}

/// Everything the renderers need beyond the catalog itself.
#[derive(Clone)]
pub struct Opts<'a> {
    /// Derives, type overrides, and the rest of the generation defaults.
    pub generate: &'a Generate,
    /// Emit feature-gated pyo3 attributes on the row structs and enums.
    pub pyo3: bool,
    /// Module the mapper imports the model types from, e.g.
    /// `crate::model` or `crate::model::shop`.
    pub model_path: String,
    /// Where the mapper's SQL lives.
    pub strategy: Strategy,
    /// Emit the `New…` insert input type alongside each row struct.
    pub inputs: bool,
    /// Name used in the generated header, never a connection string.
    pub target: &'a str,
    /// The command that reproduces this file.
    pub command: String,
    /// Struct name for a single-model run, replacing the derived one.
    pub name_override: Option<String>,
    /// Module a mapper's Python classes find `Database` in, as a path
    /// from the mapper file: `super::python` beside it, or
    /// `super::super::python` when the mappers are split by schema.
    pub bridge_path: String,
}

/// Generated source, plus anything the caller should hear about.
pub struct Rendered {
    /// The source itself.
    pub code: String,
    /// Warnings for stderr, e.g. a Postgres type with no mapping.
    pub warnings: Vec<String>,
}

/// Marker that lets proto tell its own output from a hand-written file.
pub const MARKER: &str = "@generated by proto";

/// What closes the doc comment of every method proto generates. These
/// are the methods [`crate::reconcile`] puts back when the schema moves,
/// so the file says so where somebody is about to edit one.
pub(crate) const OWNED: &str = "\
///
/// proto owns this method and rewrites it when the schema changes, so
/// edits here do not survive. Add a method of your own beside it.
";

const VERSION: &str = env!("CARGO_PKG_VERSION");

// ── Shared fragments ────────────────────────────────────────────────────────

/// The generated header every file opens with.
fn header(opts: &Opts, source: &str, kind: &str) -> String {
    header_with(opts, source, kind, "//")
}

/// Column names for a SQL clause, quoted where they need it.
pub(crate) fn column_list(columns: &[&crate::introspect::Column], sep: &str) -> String {
    columns
        .iter()
        .map(|c| crate::quoting::ident(&c.name))
        .collect::<Vec<_>>()
        .join(sep)
}

/// Indent every non-blank line, for nesting a rendered block inside
/// another. Templates are written at column zero so they look like their
/// own output; this is what puts them where they belong.
pub(crate) fn indent(text: &str, by: usize) -> String {
    let pad = " ".repeat(by);
    text.lines()
        .map(|line| {
            if line.is_empty() {
                String::from("\n")
            } else {
                format!("{pad}{line}\n")
            }
        })
        .collect()
}

/// The generated header, with the comment marker of the target language.
fn header_with(opts: &Opts, source: &str, kind: &str, prefix: &str) -> String {
    format!(
        "{prefix} {MARKER} {VERSION} — regenerate rather than rewrite.\n\
         {prefix} source: {} · {source} ({kind})\n\
         {prefix} regenerate: {}\n\n",
        opts.target, opts.command
    )
}

fn derive_line(derives: &[String], imports: &mut BTreeSet<String>) -> String {
    for d in derives {
        match d.as_str() {
            "Serialize" => {
                imports.insert("serde::Serialize".to_string());
            }
            "Deserialize" => {
                imports.insert("serde::Deserialize".to_string());
            }
            _ => {}
        }
    }
    format!("#[derive({})]\n", derives.join(", "))
}

pub(crate) fn has_serde(derives: &[String]) -> bool {
    derives
        .iter()
        .any(|d| d == "Serialize" || d == "Deserialize")
}

/// Group full paths into `use` statements, one line per parent module.
fn import_block(imports: &BTreeSet<String>) -> String {
    use_block(imports, "use")
}

/// The same, as `pub use`. A type named in a struct field has to be
/// nameable by whoever holds that struct, so an enum defined in a sibling
/// module is re-exported here rather than merely imported — otherwise
/// `model::item::ItemStatus` does not resolve and the caller has to know
/// where proto happened to put it.
fn reexport_block(imports: &BTreeSet<String>) -> String {
    use_block(imports, "pub use")
}

fn use_block(imports: &BTreeSet<String>, keyword: &str) -> String {
    if imports.is_empty() {
        return String::new();
    }
    let mut grouped: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for path in imports {
        match path.rsplit_once("::") {
            Some((parent, leaf)) => grouped.entry(parent).or_default().insert(leaf),
            None => grouped.entry("").or_default().insert(path),
        };
    }

    let mut out = String::new();
    for (parent, leaves) in grouped {
        if parent.is_empty() {
            for leaf in leaves {
                out.push_str(&format!("{keyword} {leaf};\n"));
            }
        } else if leaves.len() == 1 {
            out.push_str(&format!(
                "{keyword} {parent}::{};\n",
                leaves.iter().next().unwrap()
            ));
        } else {
            let list: Vec<&str> = leaves.into_iter().collect();
            out.push_str(&format!("{keyword} {parent}::{{{}}};\n", list.join(", ")));
        }
    }
    out.push('\n');
    out
}

fn doc_comment(text: &str, indent: &str) -> String {
    text.lines()
        .map(|line| format!("{indent}/// {}\n", line.trim_end()))
        .collect()
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn dedupe_enums(models: &[Model]) -> Vec<PgEnum> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for model in models {
        for e in &model.enums {
            if seen.insert((e.schema.clone(), e.name.clone())) {
                out.push(e.clone());
            }
        }
    }
    out
}

/// Whether `[generate.types]` names a composite. The crate supplies the
/// type then, so proto neither defines, re-exports, nor registers it —
/// any of which would collide with the import — and its attributes are
/// the crate's business rather than proto's.
pub(crate) fn overridden(c: &PgComposite, generate: &Generate) -> bool {
    generate.types.contains_key(&c.name)
}

/// The composites proto generates for a model: every one the config
/// does not override.
pub(crate) fn generated_composites<'a>(
    model: &'a Model,
    generate: &'a Generate,
) -> impl Iterator<Item = &'a PgComposite> {
    model
        .composites
        .iter()
        .filter(move |c| !overridden(c, generate))
}

/// A schema's generated composite types, once each, nested ones first.
/// Two tables naming the same type contribute it once; a type nested in
/// another is already listed before its holder within each model, and
/// stays so.
fn dedupe_composites(models: &[Model], generate: &Generate) -> Vec<PgComposite> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for model in models {
        for c in generated_composites(model, generate) {
            if seen.insert((c.schema.clone(), c.name.clone())) {
                out.push(c.clone());
            }
        }
    }
    out
}

/// Whether any table references an enum or composite type — decides if a
/// schema run needs an `enums.rs` at all. The file keeps its name from
/// when enums were the only type it held; the composites live there too.
pub fn uses_types(models: &[Model]) -> bool {
    models
        .iter()
        .any(|m| !m.enums.is_empty() || !m.composites.is_empty())
}

/// sqlx matches the type name the server reports. A type outside `public`
/// is not on the default `search_path`, so the server names it with its
/// schema and the attribute has to as well — without this a column of the
/// type fails to decode at run time, which compiling never catches.
fn sqlx_type_name(schema: &str, name: &str) -> String {
    if schema == "public" {
        name.to_string()
    } else {
        format!("{schema}.{name}")
    }
}
