//! Source emission. Nothing in this module talks to a database — output is
//! a pure function of the catalog data in [`crate::introspect`] plus the
//! options here, which is what makes the renderers testable on their own.
//!
//! - [`model`] writes the row structs, their enum types, and the insert
//!   input types.
//! - [`mapper`] writes the repository struct that runs the queries.
//! - [`sql`] writes the migration defining the server-side functions the
//!   `Server` strategy calls.

use std::collections::{BTreeMap, BTreeSet};

use crate::config::Generate;
use crate::introspect::{Model, PgEnum};

#[cfg(test)]
pub(crate) mod fixture;
pub mod mapper;
pub mod model;
pub mod plan;
pub mod sql;

/// Which SQL the mapper runs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Strategy {
    /// The statements live in the Rust source.
    #[default]
    Embedded,
    /// The statements live in Postgres functions; the mapper calls them.
    /// Pair with [`sql::migration_file`], which defines those functions.
    Server,
}

/// Everything the renderers need beyond the catalog itself.
#[derive(Clone)]
pub struct Opts<'a> {
    /// Derives, type overrides, and the rest of the generation defaults.
    pub generate: &'a Generate,
    /// Emit feature-gated pyo3 attributes on the row structs and enums.
    pub pyo3: bool,
    /// Module the mapper imports the model types from, e.g.
    /// `crate::model` or `crate::model::shop`.
    pub model_path: String,
    /// Where the mapper's SQL lives.
    pub strategy: Strategy,
    /// Emit the `New…` insert input type alongside each row struct.
    pub inputs: bool,
    /// Name used in the generated header, never a connection string.
    pub target: &'a str,
    /// The command that reproduces this file.
    pub command: String,
    /// Struct name for a single-model run, replacing the derived one.
    pub name_override: Option<String>,
}

/// Generated source, plus anything the caller should hear about.
pub struct Rendered {
    /// The source itself.
    pub code: String,
    /// Warnings for stderr, e.g. a Postgres type with no mapping.
    pub warnings: Vec<String>,
}

/// Marker that lets proto tell its own output from a hand-written file.
pub const MARKER: &str = "@generated by proto";

const VERSION: &str = env!("CARGO_PKG_VERSION");

// ── Shared fragments ────────────────────────────────────────────────────────

/// The generated header every file opens with.
fn header(opts: &Opts, source: &str, kind: &str) -> String {
    header_with(opts, source, kind, "//")
}

/// Column names for a SQL clause, quoted where they need it.
pub(crate) fn column_list(columns: &[&crate::introspect::Column], sep: &str) -> String {
    columns
        .iter()
        .map(|c| crate::quoting::ident(&c.name))
        .collect::<Vec<_>>()
        .join(sep)
}

/// Indent every non-blank line, for nesting a rendered block inside
/// another. Templates are written at column zero so they look like their
/// own output; this is what puts them where they belong.
pub(crate) fn indent(text: &str, by: usize) -> String {
    let pad = " ".repeat(by);
    text.lines()
        .map(|line| {
            if line.is_empty() {
                String::from("\n")
            } else {
                format!("{pad}{line}\n")
            }
        })
        .collect()
}

/// The generated header, with the comment marker of the target language.
fn header_with(opts: &Opts, source: &str, kind: &str, prefix: &str) -> String {
    format!(
        "{prefix} {MARKER} {VERSION} — do not edit by hand.\n\
         {prefix} source: {} · {source} ({kind})\n\
         {prefix} regenerate: {}\n\n",
        opts.target, opts.command
    )
}

fn derive_line(derives: &[String], imports: &mut BTreeSet<String>) -> String {
    for d in derives {
        match d.as_str() {
            "Serialize" => {
                imports.insert("serde::Serialize".to_string());
            }
            "Deserialize" => {
                imports.insert("serde::Deserialize".to_string());
            }
            _ => {}
        }
    }
    format!("#[derive({})]\n", derives.join(", "))
}

fn has_serde(derives: &[String]) -> bool {
    derives
        .iter()
        .any(|d| d == "Serialize" || d == "Deserialize")
}

/// Group full paths into `use` statements, one line per parent module.
fn import_block(imports: &BTreeSet<String>) -> String {
    if imports.is_empty() {
        return String::new();
    }
    let mut grouped: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for path in imports {
        match path.rsplit_once("::") {
            Some((parent, leaf)) => grouped.entry(parent).or_default().insert(leaf),
            None => grouped.entry("").or_default().insert(path),
        };
    }

    let mut out = String::new();
    for (parent, leaves) in grouped {
        if parent.is_empty() {
            for leaf in leaves {
                out.push_str(&format!("use {leaf};\n"));
            }
        } else if leaves.len() == 1 {
            out.push_str(&format!(
                "use {parent}::{};\n",
                leaves.iter().next().unwrap()
            ));
        } else {
            let list: Vec<&str> = leaves.into_iter().collect();
            out.push_str(&format!("use {parent}::{{{}}};\n", list.join(", ")));
        }
    }
    out.push('\n');
    out
}

fn doc_comment(text: &str, indent: &str) -> String {
    text.lines()
        .map(|line| format!("{indent}/// {}\n", line.trim_end()))
        .collect()
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn dedupe_enums(models: &[Model]) -> Vec<PgEnum> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for model in models {
        for e in &model.enums {
            if seen.insert((e.schema.clone(), e.name.clone())) {
                out.push(e.clone());
            }
        }
    }
    out
}

/// Whether any table references an enum type — decides if a schema run
/// needs an `enums.rs` at all.
pub fn uses_enums(models: &[Model]) -> bool {
    models.iter().any(|m| !m.enums.is_empty())
}
