//! What can go wrong, and what proto says about it.
//!
//! Every message is written for someone at a prompt: it names the file,
//! target, or table involved, and where a fix exists it says what to do.

use std::path::PathBuf;

/// A [`Result`](std::result::Result) with proto's [`Error`].
pub type Result<T> = std::result::Result<T, Error>;

/// Anything that stops a run.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// A file proto needed to read could not be read.
    #[error("could not read {path}: {source}")]
    ReadFile {
        /// The file in question.
        path: PathBuf,
        /// The underlying I/O failure.
        #[source]
        source: std::io::Error,
    },

    /// A file proto was writing could not be written.
    #[error("could not write {path}: {source}")]
    WriteFile {
        /// The file in question.
        path: PathBuf,
        /// The underlying I/O failure.
        #[source]
        source: std::io::Error,
    },

    /// The config file exists but is not valid TOML, or does not match the
    /// shape in [`crate::config`].
    #[error("invalid config file {path}: {source}")]
    ParseConfig {
        /// The config file.
        path: PathBuf,
        /// What the TOML parser objected to.
        #[source]
        source: toml::de::Error,
    },

    /// No config file, and no connection string to fall back on.
    #[error("no config file found at {path}\n  create it, set PROTO_CONFIG, or pass --url")]
    NoConfig {
        /// Where proto looked.
        path: PathBuf,
    },

    /// A target was named that the config does not define.
    #[error("database target '{name}' not found in config\n  available targets: {available}")]
    UnknownTarget {
        /// The name that was asked for.
        name: String,
        /// The names that exist, comma separated.
        available: String,
    },

    /// The config defines several databases and nothing said which to use.
    #[error(
        "no database target selected\n  pass --db <target>, set default_db, or define exactly one [databases.*]\n  available targets: {available}"
    )]
    AmbiguousTarget {
        /// The names that exist, comma separated.
        available: String,
    },

    /// The config parsed but has no `[databases.*]` table at all.
    #[error("no databases defined in {path}")]
    NoTargets {
        /// The config file.
        path: PathBuf,
    },

    /// A target was selected but no password could be found for it.
    #[error(
        "no password for target '{name}'\n  set password, password_file, password_env, PGPASSWORD, or ~/.pgpass"
    )]
    NoPassword {
        /// The database the password was wanted for.
        name: String,
    },

    /// Connecting, or a catalog query, failed.
    #[error("database error: {0}")]
    Database(#[from] sqlx::Error),

    /// The named table, view, or materialized view does not exist.
    #[error("no relation named '{schema}.{table}'")]
    NoSuchTable {
        /// Schema that was searched.
        schema: String,
        /// Relation that was not found in it.
        table: String,
    },

    /// The named schema does not exist.
    #[error("no schema named '{0}'")]
    NoSuchSchema(String),

    /// A table argument was neither `table` nor `schema.table`.
    #[error("'{0}' is not a valid table reference (expected 'table' or 'schema.table')")]
    BadTableRef(String),

    /// The destination holds a file proto did not generate. Overwriting it
    /// would discard hand-written code, so it takes `--force`.
    #[error(
        "{path} was not written by proto\n  it has no '@generated by proto' header; pass --force to overwrite it"
    )]
    NotGenerated {
        /// The file that was left alone.
        path: PathBuf,
    },

    /// The flags given do not go together.
    #[error("{0}")]
    Usage(String),
}
