use std::path::PathBuf;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("could not read {path}: {source}")]
    ReadFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },

    #[error("could not write {path}: {source}")]
    WriteFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },

    #[error("invalid config file {path}: {source}")]
    ParseConfig {
        path: PathBuf,
        #[source]
        source: toml::de::Error,
    },

    #[error("no config file found at {path}\n  create it, set PROTO_CONFIG, or pass --url")]
    NoConfig { path: PathBuf },

    #[error("database target '{name}' not found in config\n  available targets: {available}")]
    UnknownTarget { name: String, available: String },

    #[error(
        "no database target selected\n  pass --db <target>, set default_db, or define exactly one [databases.*]\n  available targets: {available}"
    )]
    AmbiguousTarget { available: String },

    #[error("no databases defined in {path}")]
    NoTargets { path: PathBuf },

    #[error(
        "no password for target '{name}'\n  set password, password_file, password_env, PGPASSWORD, or ~/.pgpass"
    )]
    NoPassword { name: String },

    #[error("database error: {0}")]
    Database(#[from] sqlx::Error),

    #[error("no relation named '{schema}.{table}'")]
    NoSuchTable { schema: String, table: String },

    #[error("no schema named '{0}'")]
    NoSuchSchema(String),

    #[error("'{0}' is not a valid table reference (expected 'table' or 'schema.table')")]
    BadTableRef(String),

    #[error(
        "{path} was not written by proto\n  it has no '@generated by proto' header; pass --force to overwrite it"
    )]
    NotGenerated { path: PathBuf },

    #[error("{0}")]
    Usage(String),
}
