//! Emits the Rust source. Nothing here talks to the database — it renders
//! whatever `introspect` handed back, so the output is a pure function of
//! the catalog plus the options.

use std::collections::{BTreeMap, BTreeSet};

use crate::config::Generate;
use crate::introspect::{Model, PgEnum, Table};
use crate::naming;
use crate::typemap;

pub struct Opts<'a> {
    pub generate: &'a Generate,
    pub pyo3: bool,
    /// Name used in the generated header, never a connection string.
    pub target: &'a str,
    /// The command that reproduces this file.
    pub command: String,
    /// Struct name for a single-model run, replacing the derived one.
    pub name_override: Option<String>,
}

pub struct Rendered {
    pub code: String,
    pub warnings: Vec<String>,
}

/// Marker that lets proto tell its own output from a hand-written file.
pub const MARKER: &str = "@generated by proto";

const VERSION: &str = env!("CARGO_PKG_VERSION");

// ── Files ───────────────────────────────────────────────────────────────────

/// One table as a standalone module. `enum_path` names the module the enum
/// types live in; `None` defines them inline, which keeps a single
/// `proto model` self-contained.
pub fn model_file(model: &Model, opts: &Opts, enum_path: Option<&str>) -> Rendered {
    let mut imports = BTreeSet::new();
    let mut warnings = Vec::new();
    let mut body = String::new();

    if enum_path.is_none() {
        for e in &model.enums {
            body.push_str(&enum_block(e, opts, &mut imports));
            body.push('\n');
        }
    } else if let Some(path) = enum_path {
        for e in &model.enums {
            imports.insert(format!("{path}::{}", naming::pascal_case(&e.name)));
        }
    }

    body.push_str(&struct_block(
        &model.table,
        opts,
        &mut imports,
        &mut warnings,
    ));

    let source = format!("{}.{}", model.table.schema, model.table.name);
    let mut code = header(opts, &source, model.table.kind.label());
    code.push_str(&import_block(&imports));
    code.push_str(&body);

    Rendered { code, warnings }
}

/// Every table in a schema as one flat file: shared enums once at the top,
/// then a struct per table. This is what `proto schema` writes to stdout.
pub fn schema_file(models: &[Model], schema: &str, opts: &Opts) -> Rendered {
    let mut imports = BTreeSet::new();
    let mut warnings = Vec::new();
    let mut body = String::new();

    for e in dedupe_enums(models) {
        body.push_str(&enum_block(&e, opts, &mut imports));
        body.push('\n');
    }
    for model in models {
        body.push_str(&struct_block(
            &model.table,
            opts,
            &mut imports,
            &mut warnings,
        ));
        body.push('\n');
    }

    let mut code = header(opts, schema, "schema");
    code.push_str(&import_block(&imports));
    code.push_str(body.trim_end());
    code.push('\n');

    Rendered { code, warnings }
}

/// The enum types of a schema, for the `enums.rs` beside the model files.
pub fn enums_file(models: &[Model], schema: &str, opts: &Opts) -> Rendered {
    let mut imports = BTreeSet::new();
    let mut body = String::new();
    for e in dedupe_enums(models) {
        body.push_str(&enum_block(&e, opts, &mut imports));
        body.push('\n');
    }

    let mut code = header(opts, schema, "enum types");
    code.push_str(&import_block(&imports));
    code.push_str(body.trim_end());
    code.push('\n');

    Rendered {
        code,
        warnings: Vec::new(),
    }
}

/// A `mod.rs` declaring the generated modules.
pub fn mod_file(modules: &[String], source: &str, opts: &Opts) -> String {
    let mut code = header(opts, source, "module list");
    for m in modules {
        code.push_str(&format!("pub mod {};\n", naming::ident(m)));
    }
    code
}

// ── Blocks ──────────────────────────────────────────────────────────────────

fn header(opts: &Opts, source: &str, kind: &str) -> String {
    format!(
        "// {MARKER} {VERSION} — do not edit by hand.\n\
         // source: {} · {source} ({kind})\n\
         // regenerate: {}\n\n",
        opts.target, opts.command
    )
}

fn struct_block(
    table: &Table,
    opts: &Opts,
    imports: &mut BTreeSet<String>,
    warnings: &mut Vec<String>,
) -> String {
    let name = opts
        .name_override
        .clone()
        .unwrap_or_else(|| naming::pascal_case(&table.name));
    let mut out = String::new();

    if let Some(comment) = &table.comment {
        out.push_str(&doc_comment(comment, ""));
    }
    if !table.primary_key.is_empty() {
        out.push_str(&format!(
            "/// Primary key: `{}`.\n",
            table.primary_key.join("`, `")
        ));
    }
    if !table.kind.nullability_is_known() {
        if !out.is_empty() {
            out.push_str("///\n");
        }
        out.push_str(&format!(
            "/// Every column of a {} reports as nullable, so every field\n\
             /// here is `Option`. Tighten by hand where you know better.\n",
            table.kind.label()
        ));
    }

    out.push_str(&derive_line(&opts.generate.derives, imports));
    if opts.pyo3 {
        // `get_all, set_all` rather than a `#[pyo3(get, set)]` on every
        // field: pyclass never sees a field-level `cfg_attr` (it is expanded
        // after the macro runs), so per-field gating does not compile.
        out.push_str(&format!(
            "#[cfg_attr(feature = \"{}\", pyo3::pyclass(get_all, set_all))]\n",
            opts.generate.pyo3_feature
        ));
    }
    out.push_str(&format!("pub struct {name} {{\n"));

    let serde = has_serde(&opts.generate.derives);
    for column in &table.columns {
        let mapped = typemap::map(&column.ty, &opts.generate.types);
        for import in &mapped.imports {
            imports.insert(import.clone());
        }

        if let Some(unknown) = &mapped.unmapped {
            out.push_str(&format!(
                "    // TODO: unmapped Postgres type `{unknown}` — set \
                 [generate.types] {unknown} = \"...\"\n"
            ));
            warnings.push(format!(
                "{}.{}.{}: unmapped Postgres type '{unknown}', using String",
                table.schema, table.name, column.name
            ));
        }
        if let Some(comment) = &column.comment {
            out.push_str(&doc_comment(comment, "    "));
        }

        let field = naming::ident(&column.name);
        if field.trim_start_matches("r#") != column.name {
            out.push_str(&format!(
                "    #[sqlx(rename = \"{}\")]\n",
                escape(&column.name)
            ));
            if serde {
                out.push_str(&format!(
                    "    #[serde(rename = \"{}\")]\n",
                    escape(&column.name)
                ));
            }
        }
        let ty = if column.not_null {
            mapped.text
        } else {
            format!("Option<{}>", mapped.text)
        };
        out.push_str(&format!("    pub {field}: {ty},\n"));
    }

    out.push_str("}\n");
    out
}

fn enum_block(e: &PgEnum, opts: &Opts, imports: &mut BTreeSet<String>) -> String {
    let name = naming::pascal_case(&e.name);
    let variants: Vec<String> = e.labels.iter().map(|l| naming::pascal_case(l)).collect();
    // Only lean on `rename_all` when every label survives the round trip;
    // otherwise each variant carries its own literal.
    let round_trips = e
        .labels
        .iter()
        .zip(&variants)
        .all(|(label, variant)| &naming::snake_case(variant) == label);

    let mut out = format!("/// The `{}.{}` enum type.\n", e.schema, e.name);
    out.push_str(&derive_line(&opts.generate.enum_derives, imports));
    if round_trips {
        out.push_str(&format!(
            "#[sqlx(type_name = \"{}\", rename_all = \"snake_case\")]\n",
            escape(&e.name)
        ));
        if has_serde(&opts.generate.enum_derives) {
            out.push_str("#[serde(rename_all = \"snake_case\")]\n");
        }
    } else {
        out.push_str(&format!("#[sqlx(type_name = \"{}\")]\n", escape(&e.name)));
    }
    if opts.pyo3 {
        out.push_str(&format!(
            "#[cfg_attr(feature = \"{}\", pyo3::pyclass(eq, eq_int))]\n",
            opts.generate.pyo3_feature
        ));
    }
    out.push_str(&format!("pub enum {name} {{\n"));
    for (label, variant) in e.labels.iter().zip(&variants) {
        if !round_trips {
            out.push_str(&format!("    #[sqlx(rename = \"{}\")]\n", escape(label)));
            if has_serde(&opts.generate.enum_derives) {
                out.push_str(&format!("    #[serde(rename = \"{}\")]\n", escape(label)));
            }
        }
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("}\n");
    out
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn derive_line(derives: &[String], imports: &mut BTreeSet<String>) -> String {
    for d in derives {
        match d.as_str() {
            "Serialize" => {
                imports.insert("serde::Serialize".to_string());
            }
            "Deserialize" => {
                imports.insert("serde::Deserialize".to_string());
            }
            _ => {}
        }
    }
    format!("#[derive({})]\n", derives.join(", "))
}

fn has_serde(derives: &[String]) -> bool {
    derives
        .iter()
        .any(|d| d == "Serialize" || d == "Deserialize")
}

/// Group full paths into `use` statements, one line per parent module.
fn import_block(imports: &BTreeSet<String>) -> String {
    if imports.is_empty() {
        return String::new();
    }
    let mut grouped: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for path in imports {
        match path.rsplit_once("::") {
            Some((parent, leaf)) => grouped.entry(parent).or_default().insert(leaf),
            None => grouped.entry("").or_default().insert(path),
        };
    }

    let mut out = String::new();
    for (parent, leaves) in grouped {
        if parent.is_empty() {
            for leaf in leaves {
                out.push_str(&format!("use {leaf};\n"));
            }
        } else if leaves.len() == 1 {
            out.push_str(&format!(
                "use {parent}::{};\n",
                leaves.iter().next().unwrap()
            ));
        } else {
            let list: Vec<&str> = leaves.into_iter().collect();
            out.push_str(&format!("use {parent}::{{{}}};\n", list.join(", ")));
        }
    }
    out.push('\n');
    out
}

fn doc_comment(text: &str, indent: &str) -> String {
    text.lines()
        .map(|line| format!("{indent}/// {}\n", line.trim_end()))
        .collect()
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn dedupe_enums(models: &[Model]) -> Vec<PgEnum> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for model in models {
        for e in &model.enums {
            if seen.insert((e.schema.clone(), e.name.clone())) {
                out.push(e.clone());
            }
        }
    }
    out
}

/// Whether a table references any enum type — used to decide if a schema
/// run needs an `enums.rs` at all.
pub fn uses_enums(models: &[Model]) -> bool {
    models.iter().any(|m| !m.enums.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::introspect::{Column, PgType, RelKind};

    fn table() -> Table {
        Table {
            schema: "arboreal".into(),
            name: "species".into(),
            kind: RelKind::Table,
            comment: None,
            columns: vec![
                Column {
                    name: "id".into(),
                    ty: PgType::Scalar("uuid".into()),
                    not_null: true,
                    comment: None,
                    has_default: true,
                    generated: false,
                },
                Column {
                    name: "notes".into(),
                    ty: PgType::Scalar("text".into()),
                    not_null: false,
                    comment: Some("Free text".into()),
                    has_default: false,
                    generated: false,
                },
            ],
            primary_key: vec!["id".into()],
        }
    }

    fn render(pyo3: bool) -> Rendered {
        let generate = Generate::default();
        let model = Model {
            table: table(),
            enums: Vec::new(),
        };
        let opts = Opts {
            generate: &generate,
            pyo3,
            target: "canopy_dev",
            command: "proto model arboreal.species".into(),
            name_override: None,
        };
        model_file(&model, &opts, None)
    }

    #[test]
    fn nullable_columns_become_option() {
        let out = render(false).code;
        assert!(out.contains("pub id: Uuid,"), "{out}");
        assert!(out.contains("pub notes: Option<String>,"), "{out}");
        assert!(out.contains("use uuid::Uuid;"), "{out}");
        assert!(out.contains(MARKER), "{out}");
        assert!(!out.contains("pyo3"), "{out}");
    }

    #[test]
    fn pyo3_is_feature_gated() {
        let out = render(true).code;
        assert!(
            out.contains("#[cfg_attr(feature = \"python\", pyo3::pyclass(get_all, set_all))]"),
            "{out}"
        );
        // A field-level cfg_attr would not compile: pyclass runs before
        // cfg_attr expands, so the `pyo3` field attribute is left orphaned.
        assert!(!out.contains("pyo3(get, set)"), "{out}");
    }

    #[test]
    fn enum_labels_that_round_trip_use_rename_all() {
        let generate = Generate::default();
        let mut imports = BTreeSet::new();
        let opts = Opts {
            generate: &generate,
            pyo3: false,
            target: "t",
            command: "c".into(),
            name_override: None,
        };
        let e = PgEnum {
            schema: "arboreal".into(),
            name: "tree_status".into(),
            labels: vec!["alive".into(), "needs_work".into()],
        };
        let out = enum_block(&e, &opts, &mut imports);
        assert!(out.contains("rename_all = \"snake_case\""), "{out}");
        assert!(out.contains("    Alive,"), "{out}");
        assert!(out.contains("    NeedsWork,"), "{out}");
    }

    #[test]
    fn odd_enum_labels_get_explicit_renames() {
        let generate = Generate::default();
        let mut imports = BTreeSet::new();
        let opts = Opts {
            generate: &generate,
            pyo3: false,
            target: "t",
            command: "c".into(),
            name_override: None,
        };
        let e = PgEnum {
            schema: "public".into(),
            name: "grade".into(),
            labels: vec!["A+".into(), "B-".into()],
        };
        let out = enum_block(&e, &opts, &mut imports);
        assert!(out.contains("#[sqlx(rename = \"A+\")]"), "{out}");
        assert!(!out.contains("rename_all"), "{out}");
    }

    #[test]
    fn imports_group_by_parent() {
        let mut imports = BTreeSet::new();
        imports.insert("chrono::DateTime".to_string());
        imports.insert("chrono::Utc".to_string());
        imports.insert("uuid::Uuid".to_string());
        let out = import_block(&imports);
        assert!(out.contains("use chrono::{DateTime, Utc};"), "{out}");
        assert!(out.contains("use uuid::Uuid;"), "{out}");
    }
}
